name: Docker Test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, edited, reopened ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Create docker network
        run: docker network create selenoid
      - name: Docker Compose
        run: docker compose up